# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accomplishments',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='body',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='conclusion',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
