# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_auto_20180326_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='video',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='accomplishments',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='body',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='conclusion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
