# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_auto_20180430_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 9, 12, 3, 7, 393000)),
        ),
    ]
