# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0004_pitch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='date',
        ),
        migrations.AddField(
            model_name='pitch',
            name='pitch_submitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 9, 12, 4, 2, 985000)),
        ),
    ]
